import unittest
from datetime import datetime, timedelta, timezone

from packages.store_core import StoreControlPlane
from packages.store_core.listing_gateway import reconcile_approved_listing
from packages.store_core.offline_listing_contracts import build_coupang_listing_review
from packages.store_core.supplier_file_contracts import HEADERS, parse_supplier_csv
from packages.store_core.sqlite_repository import SQLiteRepository


def listing_fixture():
    return {
        "displayCategoryCode": 123, "sellerProductName": "Synthetic product", "vendorId": "fixture-vendor",
        "saleStartedAt": "2026-09-07T09:00:00", "saleEndedAt": "2026-10-07T09:00:00",
        "deliveryMethod": "SEQUENCIAL", "deliveryCompanyCode": "KDEXP", "deliveryChargeType": "FREE",
        "deliveryCharge": 0, "freeShipOverAmount": 0, "deliveryChargeOnReturn": 3000,
        "remoteAreaDeliverable": "N", "unionDeliveryType": "NOT_UNION_DELIVERY",
        "returnCenterCode": "fixture-center", "returnChargeName": "PRIVATE FIXTURE",
        "companyContactNumber": "PRIVATE FIXTURE", "returnZipCode": "PRIVATE FIXTURE",
        "returnAddress": "PRIVATE FIXTURE", "returnAddressDetail": "PRIVATE FIXTURE",
        "returnCharge": 3000, "outboundShippingPlaceCode": 123, "vendorUserId": "PRIVATE FIXTURE",
        "requested": False, "items": [{
            "itemName": "Synthetic item", "originalPrice": 1000, "salePrice": 1000,
            "maximumBuyCount": 3, "maximumBuyForPerson": 0, "maximumBuyForPersonPeriod": 1,
            "outboundShippingTimeDay": 1, "unitCount": 1, "adultOnly": "EVERYONE", "taxType": "TAX",
            "parallelImported": "NOT_PARALLEL_IMPORTED", "overseasPurchased": "NOT_OVERSEAS_PURCHASED",
            "pccNeeded": False, "externalVendorSku": "001", "offerCondition": "NEW",
            "certifications": [{"certificationType": "NOT_REQUIRED", "certificationCode": ""}],
            "images": [{"imageOrder": 0, "imageType": "REPRESENTATION", "vendorPath": "https://fixture.invalid/product.png"}],
            "attributes": [{"attributeTypeName": "수량", "attributeValueName": "1개"}],
            "notices": [{"noticeCategoryName": "fixture-notice", "noticeCategoryDetailName": "제조자", "content": "Synthetic manufacturer"}],
            "contents": [{"contentsType": "TEXT", "contentDetails": [{"detailType": "TEXT", "content": "Synthetic content"}]}]
        }]
    }


class ListingReadbackGatewayTests(unittest.TestCase):
    def test_service_wrapper_preserves_fixture_only_readback_status(self):
        now = datetime(2026, 9, 7, tzinfo=timezone.utc)
        csv = ','.join(HEADERS) + '\n001,000123,fixture-model,fixture-brand,fixture-spec,blue,one,10,500,KRW,2026-09-07T00:00:00+00:00\n'
        report = parse_supplier_csv(csv.encode(), supplier_ref="fixture-supplier")
        metadata = {"fixtureSchema": "listing-category-v1", "categoryCode": 123,
                    "requiredAttributes": ["수량"], "noticeCategory": "fixture-notice",
                    "requiredNotices": ["제조자"], "certificationRequired": False}
        repo = SQLiteRepository(":memory:")
        service = StoreControlPlane(repo, lambda: now)
        context = service.bootstrap_tenant("Listing", "listing@example.test")
        review = build_coupang_listing_review(
            listing_fixture(), report, metadata, tenant_ref=context.tenant_id,
            connection_ref="fixture-channel", vendor_id="fixture-vendor", supplier_sku="001",
            rights_digest="a" * 64, now=now, observed_at=now,
            expires_at=now + timedelta(seconds=60), reserved_quantity=2,
            safety_buffer=1, quantity_cap=6, variable_cost_minor=50, fee_rate="0.05")
        readback = listing_fixture()
        readback.update(sellerProductId=9007199254740997, statusName="승인완료")
        readback["items"][0].update(sellerProductItemId=9007199254740998,
                                    isAutoGenerated="false", vendorItemId=9007199254740999)
        result = reconcile_approved_listing(
            service, context, review,
            connection_ref="fixture-channel",
            creation_response={"code": "SUCCESS", "data": 9007199254740997},
            original_payload=listing_fixture(), readback={"code": "SUCCESS", "data": readback},
            observed_at=now)
        self.assertEqual("MATCHED_APPROVED_FIXTURE", result.decision)
        self.assertFalse(result.real_listing_confirmed)
        self.assertFalse(result.resend_authorized)
        repo.close()


if __name__ == "__main__":
    unittest.main()
